	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ClienteDTO 	    implements IDTO
	    {
				private String dni;
				public String getDni () { return dni; } 
				public void setDni  (String value) { dni = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private String apellidos;
				public String getApellidos () { return apellidos; } 
				public void setApellidos  (String value) { apellidos = value;  } 
				    	 
				private ArrayList<Integer> factura_oid;
				public ArrayList<Integer>  getFactura_oid () { return factura_oid; } 
				public void setFactura_oid (ArrayList<Integer> value) { factura_oid = value;  } 
				    	 
				private ArrayList<Integer> cobro_oid;
				public ArrayList<Integer>  getCobro_oid () { return cobro_oid; } 
				public void setCobro_oid (ArrayList<Integer> value) { cobro_oid = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer negocio_oid;
				public Integer  getNegocio_oid () { return negocio_oid; } 
				public void setNegocio_oid (Integer value) { negocio_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Dni", this.dni);
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Apellidos", this.apellidos);
				

						if (this.factura_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.factura_oid.size(); ++i)
							{
								jsonArray.put(this.factura_oid.get(i));
							}
							json.put("Factura_oid", jsonArray);
						}
		

						if (this.cobro_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.cobro_oid.size(); ++i)
							{
								jsonArray.put(this.cobro_oid.get(i));
							}
							json.put("Cobro_oid", jsonArray);
						}
		
				
						  json.put("Id", this.id.intValue());
				

						if (this.negocio_oid != null)
						{
							json.put("Negocio_oid", this.negocio_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	