	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class CobroDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private float monto;
				public float getMonto () { return monto; } 
				public void setMonto  (float value) { monto = value;  } 
				    	 
				private Integer comanda_oid;
				public Integer  getComanda_oid () { return comanda_oid; } 
				public void setComanda_oid (Integer value) { comanda_oid = value;  } 
				    	 
				private Integer cliente_oid;
				public Integer  getCliente_oid () { return cliente_oid; } 
				public void setCliente_oid (Integer value) { cliente_oid = value;  } 
				    	 
				private String tipoDeCobro;
				public String getTipoDeCobro () { return tipoDeCobro; } 
				public void setTipoDeCobro  (String value) { tipoDeCobro = value;  } 
				    	 
				private Integer tipoCobro_oid;
				public Integer  getTipoCobro_oid () { return tipoCobro_oid; } 
				public void setTipoCobro_oid (Integer value) { tipoCobro_oid = value;  } 
				    	 
				private ArrayList<Integer> caja_oid;
				public ArrayList<Integer>  getCaja_oid () { return caja_oid; } 
				public void setCaja_oid (ArrayList<Integer> value) { caja_oid = value;  } 
				    	 
				private String numeroTransaccion;
				public String getNumeroTransaccion () { return numeroTransaccion; } 
				public void setNumeroTransaccion  (String value) { numeroTransaccion = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Monto", this.monto);
				

						if (this.comanda_oid != null)
						{
							json.put("Comanda_oid", this.comanda_oid.intValue());
						}

						if (this.cliente_oid != null)
						{
							json.put("Cliente_oid", this.cliente_oid.intValue());
						}
				
						  json.put("TipoDeCobro", this.tipoDeCobro);
				

						if (this.tipoCobro_oid != null)
						{
							json.put("TipoCobro_oid", this.tipoCobro_oid.intValue());
						}

						if (this.caja_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.caja_oid.size(); ++i)
							{
								jsonArray.put(this.caja_oid.get(i));
							}
							json.put("Caja_oid", jsonArray);
						}
		
				
						  json.put("NumeroTransaccion", this.numeroTransaccion);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	