	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ComandaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private EstadoComanda estadoPedido;
				public EstadoComanda getEstadoPedido () { return estadoPedido; } 
				public void setEstadoPedido  (EstadoComanda value) { estadoPedido = value;  } 
				    	 
				private Integer camarero_oid;
				public Integer  getCamarero_oid () { return camarero_oid; } 
				public void setCamarero_oid (Integer value) { camarero_oid = value;  } 
				    	 
				private ArrayList<LineaComandaDTO> lineaComanda;
				public ArrayList<LineaComandaDTO> getLineaComanda () { return lineaComanda; } 
				public void setLineaComanda (ArrayList<LineaComandaDTO> value) { lineaComanda = value;  } 
				    	 
				private ArrayList<Integer> pago_oid;
				public ArrayList<Integer>  getPago_oid () { return pago_oid; } 
				public void setPago_oid (ArrayList<Integer> value) { pago_oid = value;  } 
				    	 
				private Integer mesa_oid;
				public Integer  getMesa_oid () { return mesa_oid; } 
				public void setMesa_oid (Integer value) { mesa_oid = value;  } 
				    	 
				private Integer factura_oid;
				public Integer  getFactura_oid () { return factura_oid; } 
				public void setFactura_oid (Integer value) { factura_oid = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("EstadoPedido", this.estadoPedido.getRawValue());
				

						if (this.camarero_oid != null)
						{
							json.put("Camarero_oid", this.camarero_oid.intValue());
						}

						if (this.lineaComanda != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.lineaComanda.size(); ++i)
							{
								jsonArray.put(this.lineaComanda.get(i).toJSON());
							}
							json.put("LineaComanda", jsonArray);
						}

						if (this.pago_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.pago_oid.size(); ++i)
							{
								jsonArray.put(this.pago_oid.get(i));
							}
							json.put("Pago_oid", jsonArray);
						}
		

						if (this.mesa_oid != null)
						{
							json.put("Mesa_oid", this.mesa_oid.intValue());
						}

						if (this.factura_oid != null)
						{
							json.put("Factura_oid", this.factura_oid.intValue());
						}
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	