	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class EmpleadoDTO 	    implements IDTO
	    {
				private ArrayList<Integer> rol_oid;
				public ArrayList<Integer>  getRol_oid () { return rol_oid; } 
				public void setRol_oid (ArrayList<Integer> value) { rol_oid = value;  } 
				    	 
				private Integer negocio_oid;
				public Integer  getNegocio_oid () { return negocio_oid; } 
				public void setNegocio_oid (Integer value) { negocio_oid = value;  } 
				    	 
				private Integer dNI;
				public Integer getDNI () { return dNI; } 
				public void setDNI  (Integer value) { dNI = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private String apellidos;
				public String getApellidos () { return apellidos; } 
				public void setApellidos  (String value) { apellidos = value;  } 
				    	 
				private String pass;
				public String getPass () { return pass; } 
				public void setPass  (String value) { pass = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.rol_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.rol_oid.size(); ++i)
							{
								jsonArray.put(this.rol_oid.get(i));
							}
							json.put("Rol_oid", jsonArray);
						}
		

						if (this.negocio_oid != null)
						{
							json.put("Negocio_oid", this.negocio_oid.intValue());
						}
				
						  json.put("DNI", this.dNI.intValue());
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Apellidos", this.apellidos);
				
				
						  json.put("Pass", this.pass);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	