	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class EmpresaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private String direccion;
				public String getDireccion () { return direccion; } 
				public void setDireccion  (String value) { direccion = value;  } 
				    	 
				private Integer dueño_oid;
				public Integer  getDueño_oid () { return dueño_oid; } 
				public void setDueño_oid (Integer value) { dueño_oid = value;  } 
				    	 
				private ArrayList<Integer> negocio_oid;
				public ArrayList<Integer>  getNegocio_oid () { return negocio_oid; } 
				public void setNegocio_oid (ArrayList<Integer> value) { negocio_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Direccion", this.direccion);
				

						if (this.dueño_oid != null)
						{
							json.put("Dueño_oid", this.dueño_oid.intValue());
						}

						if (this.negocio_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.negocio_oid.size(); ++i)
							{
								jsonArray.put(this.negocio_oid.get(i));
							}
							json.put("Negocio_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	