	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class FacturaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String numero;
				public String getNumero () { return numero; } 
				public void setNumero  (String value) { numero = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Double precio;
				public Double getPrecio () { return precio; } 
				public void setPrecio  (Double value) { precio = value;  } 
				    	 
				private String descripcion;
				public String getDescripcion () { return descripcion; } 
				public void setDescripcion  (String value) { descripcion = value;  } 
				    	 
				private Integer comanda_oid;
				public Integer  getComanda_oid () { return comanda_oid; } 
				public void setComanda_oid (Integer value) { comanda_oid = value;  } 
				    	 
				private Integer cliente_oid;
				public Integer  getCliente_oid () { return cliente_oid; } 
				public void setCliente_oid (Integer value) { cliente_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Numero", this.numero);
				
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				
				
						  json.put("Precio", this.precio);
				
				
						  json.put("Descripcion", this.descripcion);
				

						if (this.comanda_oid != null)
						{
							json.put("Comanda_oid", this.comanda_oid.intValue());
						}

						if (this.cliente_oid != null)
						{
							json.put("Cliente_oid", this.cliente_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	