	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class LineaComandaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer comanda_oid;
				public Integer  getComanda_oid () { return comanda_oid; } 
				public void setComanda_oid (Integer value) { comanda_oid = value;  } 
				    	 
				private Integer plato_oid;
				public Integer  getPlato_oid () { return plato_oid; } 
				public void setPlato_oid (Integer value) { plato_oid = value;  } 
				    	 
				private Integer cantidad;
				public Integer getCantidad () { return cantidad; } 
				public void setCantidad  (Integer value) { cantidad = value;  } 
				    	 
				private Integer menu_oid;
				public Integer  getMenu_oid () { return menu_oid; } 
				public void setMenu_oid (Integer value) { menu_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				

						if (this.comanda_oid != null)
						{
							json.put("Comanda_oid", this.comanda_oid.intValue());
						}

						if (this.plato_oid != null)
						{
							json.put("Plato_oid", this.plato_oid.intValue());
						}
				
						  json.put("Cantidad", this.cantidad.intValue());
				

						if (this.menu_oid != null)
						{
							json.put("Menu_oid", this.menu_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	