	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class LineaPlatoDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Double cantidad;
				public Double getCantidad () { return cantidad; } 
				public void setCantidad  (Double value) { cantidad = value;  } 
				    	 
				private Integer producto_oid;
				public Integer  getProducto_oid () { return producto_oid; } 
				public void setProducto_oid (Integer value) { producto_oid = value;  } 
				    	 
				private Integer plato_oid;
				public Integer  getPlato_oid () { return plato_oid; } 
				public void setPlato_oid (Integer value) { plato_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Cantidad", this.cantidad);
				

						if (this.producto_oid != null)
						{
							json.put("Producto_oid", this.producto_oid.intValue());
						}

						if (this.plato_oid != null)
						{
							json.put("Plato_oid", this.plato_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	