	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class PagoDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private ArrayList<Integer> idPedidoProveedor;
				public ArrayList<Integer> getIdPedidoProveedor () { return idPedidoProveedor; } 
				public void setIdPedidoProveedor  (ArrayList<Integer> value) { idPedidoProveedor = value;  } 
				    	 
				private Double monto;
				public Double getMonto () { return monto; } 
				public void setMonto  (Double value) { monto = value;  } 
				    	 
				private ArrayList<Integer> compraProveedor_oid;
				public ArrayList<Integer>  getCompraProveedor_oid () { return compraProveedor_oid; } 
				public void setCompraProveedor_oid (ArrayList<Integer> value) { compraProveedor_oid = value;  } 
				    	 
				private java.util.Date fechaPago;
				public java.util.Date getFechaPago () { return fechaPago; } 
				public void setFechaPago  (java.util.Date value) { fechaPago = value;  } 
				    	 
				private Integer tipoPago_oid;
				public Integer  getTipoPago_oid () { return tipoPago_oid; } 
				public void setTipoPago_oid (Integer value) { tipoPago_oid = value;  } 
				    	 
				private Integer numeroDocumento;
				public Integer getNumeroDocumento () { return numeroDocumento; } 
				public void setNumeroDocumento  (Integer value) { numeroDocumento = value;  } 
				    	 
				private ArrayList<Integer> caja_oid;
				public ArrayList<Integer>  getCaja_oid () { return caja_oid; } 
				public void setCaja_oid (ArrayList<Integer> value) { caja_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
					    if (this.idPedidoProveedor != null){											
						  json.put("IdPedidoProveedor", this.idPedidoProveedor.intValue());
				
						}
				
						  json.put("Monto", this.monto);
				

						if (this.compraProveedor_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.compraProveedor_oid.size(); ++i)
							{
								jsonArray.put(this.compraProveedor_oid.get(i));
							}
							json.put("CompraProveedor_oid", jsonArray);
						}
		
				
						  json.put("FechaPago", DateUtils.dateToFormatString(this.fechaPago));
				

						if (this.tipoPago_oid != null)
						{
							json.put("TipoPago_oid", this.tipoPago_oid.intValue());
						}
				
						  json.put("NumeroDocumento", this.numeroDocumento.intValue());
				

						if (this.caja_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.caja_oid.size(); ++i)
							{
								jsonArray.put(this.caja_oid.get(i));
							}
							json.put("Caja_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	