	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ProveedorDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private String numeroTelefono;
				public String getNumeroTelefono () { return numeroTelefono; } 
				public void setNumeroTelefono  (String value) { numeroTelefono = value;  } 
				    	 
				private ArrayList<Integer> compraProveedor_oid;
				public ArrayList<Integer>  getCompraProveedor_oid () { return compraProveedor_oid; } 
				public void setCompraProveedor_oid (ArrayList<Integer> value) { compraProveedor_oid = value;  } 
				    	 
				private String email;
				public String getEmail () { return email; } 
				public void setEmail  (String value) { email = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("NumeroTelefono", this.numeroTelefono);
				

						if (this.compraProveedor_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.compraProveedor_oid.size(); ++i)
							{
								jsonArray.put(this.compraProveedor_oid.get(i));
							}
							json.put("CompraProveedor_oid", jsonArray);
						}
		
				
						  json.put("Email", this.email);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	