	
		package tpvhostGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class RolDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer cajero_oid;
				public Integer  getCajero_oid () { return cajero_oid; } 
				public void setCajero_oid (Integer value) { cajero_oid = value;  } 
				    	 
				private Integer cocinero_oid;
				public Integer  getCocinero_oid () { return cocinero_oid; } 
				public void setCocinero_oid (Integer value) { cocinero_oid = value;  } 
				    	 
				private Integer encargado_oid;
				public Integer  getEncargado_oid () { return encargado_oid; } 
				public void setEncargado_oid (Integer value) { encargado_oid = value;  } 
				    	 
				private Integer camarero_oid;
				public Integer  getCamarero_oid () { return camarero_oid; } 
				public void setCamarero_oid (Integer value) { camarero_oid = value;  } 
				    	 
				private Empleo empleo;
				public Empleo getEmpleo () { return empleo; } 
				public void setEmpleo  (Empleo value) { empleo = value;  } 
				    	 
				private Integer empleado_oid;
				public Integer  getEmpleado_oid () { return empleado_oid; } 
				public void setEmpleado_oid (Integer value) { empleado_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				

						if (this.cajero_oid != null)
						{
							json.put("Cajero_oid", this.cajero_oid.intValue());
						}

						if (this.cocinero_oid != null)
						{
							json.put("Cocinero_oid", this.cocinero_oid.intValue());
						}

						if (this.encargado_oid != null)
						{
							json.put("Encargado_oid", this.encargado_oid.intValue());
						}

						if (this.camarero_oid != null)
						{
							json.put("Camarero_oid", this.camarero_oid.intValue());
						}
				
						  json.put("Empleo", this.empleo.getRawValue());
				

						if (this.empleado_oid != null)
						{
							json.put("Empleado_oid", this.empleado_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	