
package tpvhostGenTpvhostRESTAzure.uiModels.DTOA;

import tpvhostGenTpvhostRESTAzure.uiModels.DTO.*;
import tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
import tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class EmpleadoDTOA extends DTOA
{
	// region - Members, getters and setters

	
	private Integer dNI;
	public Integer getDNI () { return dNI; }
	public void setDNI (Integer dNI) { this.dNI = dNI; }
	
	private String nombre;
	public String getNombre () { return nombre; }
	public void setNombre (String nombre) { this.nombre = nombre; }
	
	private String apellidos;
	public String getApellidos () { return apellidos; }
	public void setApellidos (String apellidos) { this.apellidos = apellidos; }
	
	private String pass;
	public String getPass () { return pass; }
	public void setPass (String pass) { this.pass = pass; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public EmpleadoDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			

			if (!JSONObject.NULL.equals(json.opt("DNI")))
			{
			 
				this.dNI = (Integer) json.opt("DNI");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Nombre")))
			{
			 
				this.nombre = (String) json.opt("Nombre");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Apellidos")))
			{
			 
				this.apellidos = (String) json.opt("Apellidos");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Pass")))
			{
			 
				this.pass = (String) json.opt("Pass");
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			
		
		  if (this.dNI != null)
			json.put("DNI", this.dNI.intValue());
		
		
		  if (this.nombre != null)
			json.put("Nombre", this.nombre);
		
		
		  if (this.apellidos != null)
			json.put("Apellidos", this.apellidos);
		
		
		  if (this.pass != null)
			json.put("Pass", this.pass);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		EmpleadoDTO dto = new EmpleadoDTO ();
		
		// Attributes
		
		
	dto.setDNI (this.getDNI());

	dto.setNombre (this.getNombre());

	dto.setApellidos (this.getApellidos());

	dto.setPass (this.getPass());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	