
package tpvhostGenTpvhostRESTAzure.uiModels.DTOA;

import tpvhostGenTpvhostRESTAzure.uiModels.DTO.*;
import tpvhostGenTpvhostRESTAzure.uiModels.DTO.utils.*;
import tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class NegocioDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String nombre;
	public String getNombre () { return nombre; }
	public void setNombre (String nombre) { this.nombre = nombre; }
	
	private String direccion;
	public String getDireccion () { return direccion; }
	public void setDireccion (String direccion) { this.direccion = direccion; }
	
	private String ciudad;
	public String getCiudad () { return ciudad; }
	public void setCiudad (String ciudad) { this.ciudad = ciudad; }
	
	private String cp;
	public String getCp () { return cp; }
	public void setCp (String cp) { this.cp = cp; }
	
	private String provincia;
	public String getProvincia () { return provincia; }
	public void setProvincia (String provincia) { this.provincia = provincia; }
	
	private String pais;
	public String getPais () { return pais; }
	public void setPais (String pais) { this.pais = pais; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public NegocioDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Nombre")))
			{
			 
				this.nombre = (String) json.opt("Nombre");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Direccion")))
			{
			 
				this.direccion = (String) json.opt("Direccion");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Ciudad")))
			{
			 
				this.ciudad = (String) json.opt("Ciudad");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Cp")))
			{
			 
				this.cp = (String) json.opt("Cp");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Provincia")))
			{
			 
				this.provincia = (String) json.opt("Provincia");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Pais")))
			{
			 
				this.pais = (String) json.opt("Pais");
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.nombre != null)
			json.put("Nombre", this.nombre);
		
		
		  if (this.direccion != null)
			json.put("Direccion", this.direccion);
		
		
		  if (this.ciudad != null)
			json.put("Ciudad", this.ciudad);
		
		
		  if (this.cp != null)
			json.put("Cp", this.cp);
		
		
		  if (this.provincia != null)
			json.put("Provincia", this.provincia);
		
		
		  if (this.pais != null)
			json.put("Pais", this.pais);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		NegocioDTO dto = new NegocioDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setNombre (this.getNombre());

	dto.setDireccion (this.getDireccion());

	dto.setCiudad (this.getCiudad());

	dto.setCp (this.getCp());

	dto.setProvincia (this.getProvincia());

	dto.setPais (this.getPais());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	