//
// Enumerations.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation


enum EstadoComanda: Int
{
	case Comanda = 1
	case Preparado = 2
	case Rechazado = 3
}

enum Empleo: Int
{
	case Cajero = 1
	case Cocinero = 2
	case Camarero = 3
	case Encargado = 4
}

enum EstadoCompraProveedor: Int
{
	case Pendiente = 1
	case Pagado = 2
	case Anulado = 3
}

	