	
		//
		// CajaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CajaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var fondo: Double?;
				    	 
		 
				var negocio_oid: Int?;
				    	 
		 
				var cajero_oid: [Int]?;
				    	 
		 
				var pago_oid: [Int]?;
				    	 
		 
				var saldo: Double?;
				    	 
		 
				var cobro_oid: [Int]?;
				    	 
		 
				var descripcion: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["fondo"] = self.fondo;
				

					dictionary["negocio_oid"] = self.negocio_oid;
			

					dictionary["cajero_oid"] = self.cajero_oid;
			

					dictionary["pago_oid"] = self.pago_oid;
			

				
					dictionary["saldo"] = self.saldo;
				

					dictionary["cobro_oid"] = self.cobro_oid;
			

				
					dictionary["descripcion"] = self.descripcion;
				
						
				return dictionary;
			}
		}
		
	