	
		//
		// CompraProveedorDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CompraProveedorDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var lineaCompraProveedor: [LineaCompraProveedorDTO]?;
				    	 
		 
				var proveedor_oid: Int?;
				    	 
		 
				var negocio_oid: Int?;
				    	 
		 
				var pago_oid: [Int]?;
				    	 
		 
				var saldo: Double?;
				    	 
		 
				var estadoCompra: EstadoCompraProveedor?;
				    	 
		 
				var fecha: NSDate?;
				    	 
		 
				var total: Double?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["lineaCompraProveedor"] = NSNull();
					if (self.lineaCompraProveedor != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.lineaCompraProveedor!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["lineaCompraProveedor"] = arrayOfDictionary;
					}
			

					dictionary["proveedor_oid"] = self.proveedor_oid;
			

					dictionary["negocio_oid"] = self.negocio_oid;
			

					dictionary["pago_oid"] = self.pago_oid;
			

				
					dictionary["saldo"] = self.saldo;
				

				
					dictionary["estadoCompra"] = self.estadoCompra?.rawValue;
				

				
					dictionary["fecha"] = self.fecha?.toString();
				

				
					dictionary["total"] = self.total;
				
						
				return dictionary;
			}
		}
		
	