	
		//
		// EmpresaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class EmpresaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var direccion: String?;
				    	 
		 
				var dueño_oid: Int?;
				    	 
		 
				var negocio_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["direccion"] = self.direccion;
				

					dictionary["dueño_oid"] = self.dueño_oid;
			

					dictionary["negocio_oid"] = self.negocio_oid;
			
						
				return dictionary;
			}
		}
		
	