	
		//
		// FacturaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class FacturaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var numero: String?;
				    	 
		 
				var fecha: NSDate?;
				    	 
		 
				var precio: Double?;
				    	 
		 
				var descripcion: String?;
				    	 
		 
				var comanda_oid: Int?;
				    	 
		 
				var cliente_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["numero"] = self.numero;
				

				
					dictionary["fecha"] = self.fecha?.toString();
				

				
					dictionary["precio"] = self.precio;
				

				
					dictionary["descripcion"] = self.descripcion;
				

					dictionary["comanda_oid"] = self.comanda_oid;
			

					dictionary["cliente_oid"] = self.cliente_oid;
			
						
				return dictionary;
			}
		}
		
	