	
		//
		// LineaCompraProveedorDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class LineaCompraProveedorDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var cantidad: Int?;
				    	 
		 
				var servicio_oid: Int?;
				    	 
		 
				var compraProveedor_oid: Int?;
				    	 
		 
				var producto_oid: Int?;
				    	 
		 
				var costo: Double?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["cantidad"] = self.cantidad;
				

					dictionary["servicio_oid"] = self.servicio_oid;
			

					dictionary["compraProveedor_oid"] = self.compraProveedor_oid;
			

					dictionary["producto_oid"] = self.producto_oid;
			

				
					dictionary["costo"] = self.costo;
				
						
				return dictionary;
			}
		}
		
	