	
		//
		// LineaPlatoDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class LineaPlatoDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var cantidad: Double?;
				    	 
		 
				var producto_oid: Int?;
				    	 
		 
				var plato_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["cantidad"] = self.cantidad;
				

					dictionary["producto_oid"] = self.producto_oid;
			

					dictionary["plato_oid"] = self.plato_oid;
			
						
				return dictionary;
			}
		}
		
	