	
		//
		// NegocioDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class NegocioDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var direccion: String?;
				    	 
		 
				var ciudad: String?;
				    	 
		 
				var cp: String?;
				    	 
		 
				var provincia: String?;
				    	 
		 
				var pais: String?;
				    	 
		 
				var servicios_oid: [Int]?;
				    	 
		 
				var empresa_oid: Int?;
				    	 
		 
				var mesa_oid: [Int]?;
				    	 
		 
				var caja_oid: [Int]?;
				    	 
		 
				var compraProveedor_oid: [Int]?;
				    	 
		 
				var producto_oid: [Int]?;
				    	 
		 
				var empleado_oid: [Int]?;
				    	 
		 
				var cliente_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["direccion"] = self.direccion;
				

				
					dictionary["ciudad"] = self.ciudad;
				

				
					dictionary["cp"] = self.cp;
				

				
					dictionary["provincia"] = self.provincia;
				

				
					dictionary["pais"] = self.pais;
				

					dictionary["servicios_oid"] = self.servicios_oid;
			

					dictionary["empresa_oid"] = self.empresa_oid;
			

					dictionary["mesa_oid"] = self.mesa_oid;
			

					dictionary["caja_oid"] = self.caja_oid;
			

					dictionary["compraProveedor_oid"] = self.compraProveedor_oid;
			

					dictionary["producto_oid"] = self.producto_oid;
			

					dictionary["empleado_oid"] = self.empleado_oid;
			

					dictionary["cliente_oid"] = self.cliente_oid;
			
						
				return dictionary;
			}
		}
		
	