	
		//
		// PagoDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class PagoDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var idPedidoProveedor: [Int]?;
				    	 
		 
				var monto: Double?;
				    	 
		 
				var compraProveedor_oid: [Int]?;
				    	 
		 
				var fechaPago: NSDate?;
				    	 
		 
				var tipoPago_oid: Int?;
				    	 
		 
				var numeroDocumento: Int?;
				    	 
		 
				var caja_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["idPedidoProveedor"] = self.idPedidoProveedor;
				

				
					dictionary["monto"] = self.monto;
				

					dictionary["compraProveedor_oid"] = self.compraProveedor_oid;
			

				
					dictionary["fechaPago"] = self.fechaPago?.toString();
				

					dictionary["tipoPago_oid"] = self.tipoPago_oid;
			

				
					dictionary["numeroDocumento"] = self.numeroDocumento;
				

					dictionary["caja_oid"] = self.caja_oid;
			
						
				return dictionary;
			}
		}
		
	