	
		//
		// ProductoDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ProductoDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var stock: Double?;
				    	 
		 
				var unidadMedida_oid: Int?;
				    	 
		 
				var lineaCompraProveedor: [LineaCompraProveedorDTO]?;
				    	 
		 
				var lineaPlato_oid: [Int]?;
				    	 
		 
				var negocio_oid: Int?;
				    	 
		 
				var descripcion: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["stock"] = self.stock;
				

					dictionary["unidadMedida_oid"] = self.unidadMedida_oid;
			

					dictionary["lineaCompraProveedor"] = NSNull();
					if (self.lineaCompraProveedor != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.lineaCompraProveedor!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["lineaCompraProveedor"] = arrayOfDictionary;
					}
			

					dictionary["lineaPlato_oid"] = self.lineaPlato_oid;
			

					dictionary["negocio_oid"] = self.negocio_oid;
			

				
					dictionary["descripcion"] = self.descripcion;
				
						
				return dictionary;
			}
		}
		
	