	
		//
		// ProveedorDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ProveedorDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var numeroTelefono: String?;
				    	 
		 
				var compraProveedor_oid: [Int]?;
				    	 
		 
				var email: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["numeroTelefono"] = self.numeroTelefono;
				

					dictionary["compraProveedor_oid"] = self.compraProveedor_oid;
			

				
					dictionary["email"] = self.email;
				
						
				return dictionary;
			}
		}
		
	