	
		//
		// RolDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RolDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var cajero_oid: Int?;
				    	 
		 
				var cocinero_oid: Int?;
				    	 
		 
				var encargado_oid: Int?;
				    	 
		 
				var camarero_oid: Int?;
				    	 
		 
				var empleo: Empleo?;
				    	 
		 
				var empleado_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["cajero_oid"] = self.cajero_oid;
			

					dictionary["cocinero_oid"] = self.cocinero_oid;
			

					dictionary["encargado_oid"] = self.encargado_oid;
			

					dictionary["camarero_oid"] = self.camarero_oid;
			

				
					dictionary["empleo"] = self.empleo?.rawValue;
				

					dictionary["empleado_oid"] = self.empleado_oid;
			
						
				return dictionary;
			}
		}
		
	