	
		//
		// ServicioDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ServicioDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var negocio_oid: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var costo: Double?;
				    	 
		 
				var lineaProveedor: [LineaCompraProveedorDTO]?;
				    	 
		 
				var codigoContrato: String?;
				    	 
		 
				var categoriaServicio_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["negocio_oid"] = self.negocio_oid;
			

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["costo"] = self.costo;
				

					dictionary["lineaProveedor"] = NSNull();
					if (self.lineaProveedor != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.lineaProveedor!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["lineaProveedor"] = arrayOfDictionary;
					}
			

				
					dictionary["codigoContrato"] = self.codigoContrato;
				

					dictionary["categoriaServicio_oid"] = self.categoriaServicio_oid;
			
						
				return dictionary;
			}
		}
		
	