	
		//
		// TipoCobroDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class TipoCobroDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var cobro_oid: [Int]?;
				    	 
		 
				var descripcion: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["cobro_oid"] = self.cobro_oid;
			

				
					dictionary["descripcion"] = self.descripcion;
				
						
				return dictionary;
			}
		}
		
	