	
		//
		// UnidadMedidaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class UnidadMedidaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var descripcion: String?;
				    	 
		 
				var producto_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["descripcion"] = self.descripcion;
				

					dictionary["producto_oid"] = self.producto_oid;
			
						
				return dictionary;
			}
		}
		
	