
package tpvhostGenTpvhostRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum EstadoCompraProveedor
{
	// region - Literals

	Pendiente (1)
	,	Pagado (2)
	,	Anulado (3)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	EstadoCompraProveedor (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static EstadoCompraProveedor fromRawValue (int rawValue)
	{
		EstadoCompraProveedor[] enumValues = EstadoCompraProveedor.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
