//
// CompraProveedorDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class CompraProveedorDTOA : DTOA
{
	// MARK: - Properties

	
	var saldo: Double?;
	var estadoCompra: EstadoCompraProveedor?;
	var fecha: NSDate?;
	var total: Double?;
	var id: Int?;
	
	/* Rol: CompraProveedor o--> LineaCompraProveedor */
	var lineasCompraProveedor: [LineaCompraProveedorDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.saldo = json["Saldo"].object as? Double;
		if let enumValue = json["EstadoCompra"].object as? Int
		{
			self.estadoCompra = EstadoCompraProveedor(rawValue: enumValue);
		}
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		self.total = json["Total"].object as? Double;
		self.id = json["Id"].object as? Int;
		
		if (json["LineasCompraProveedor"] != JSON.null)
		{
			self.lineasCompraProveedor = [];
			for subJson in json["LineasCompraProveedor"].arrayValue
			{
				self.lineasCompraProveedor!.append(LineaCompraProveedorDTOA(fromJSONObject: subJson));
			}
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["Saldo"] = self.saldo;
	
	

	
		dictionary["EstadoCompra"] = self.estadoCompra?.rawValue;
	
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	

	
		dictionary["Total"] = self.total;
	
	

	
		dictionary["Id"] = self.id;
	
	
		
		dictionary["LineasCompraProveedor"] = NSNull();
		if (self.lineasCompraProveedor != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.lineasCompraProveedor!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["LineasCompraProveedor"] = arrayOfDictionary;
		}

		
		
		return dictionary;
	}
}

	