//
// DuenyoRegistradoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class DuenyoRegistradoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var nombre: String?;
	var apellido: String?;
	var dni: String?;
	var telefono: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.nombre = json["Nombre"].object as? String;
		self.apellido = json["Apellido"].object as? String;
		self.dni = json["Dni"].object as? String;
		self.telefono = json["Telefono"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Apellido"] = self.apellido;
	
	

	
		dictionary["Dni"] = self.dni;
	
	

	
		dictionary["Telefono"] = self.telefono;
	
	
		
		
		
		return dictionary;
	}
}

	