//
// EmpleadoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class EmpleadoDTOA : DTOA
{
	// MARK: - Properties

	
	var dNI: Int?;
	var nombre: String?;
	var apellidos: String?;
	var pass: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.dNI = json["DNI"].object as? Int;
		self.nombre = json["Nombre"].object as? String;
		self.apellidos = json["Apellidos"].object as? String;
		self.pass = json["Pass"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["DNI"] = self.dNI;
	
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Apellidos"] = self.apellidos;
	
	

	
		dictionary["Pass"] = self.pass;
	
	
		
		
		
		return dictionary;
	}
}

	