//
// LineaCompraProveedorDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class LineaCompraProveedorDTOA : DTOA
{
	// MARK: - Properties

	
	var id: Int?;
	var cantidad: Int?;
	var costo: Double?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		
	
		self.id = json["Id"].object as? Int;
		self.cantidad = json["Cantidad"].object as? Int;
		self.costo = json["Costo"].object as? Double;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		
	

	
		dictionary["Id"] = self.id;
	
	

	
		dictionary["Cantidad"] = self.cantidad;
	
	

	
		dictionary["Costo"] = self.costo;
	
	
		
		
		
		return dictionary;
	}
}

	