//
// MenuDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class MenuDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var nombre: String?;
	var stock: Double?;
	
	/* Rol: Menu o--> LineaMenu */
	var lineasMenu: [LineaMenuDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.nombre = json["Nombre"].object as? String;
		self.stock = json["Stock"].object as? Double;
		
		if (json["LineasMenu"] != JSON.null)
		{
			self.lineasMenu = [];
			for subJson in json["LineasMenu"].arrayValue
			{
				self.lineasMenu!.append(LineaMenuDTOA(fromJSONObject: subJson));
			}
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Stock"] = self.stock;
	
	
		
		dictionary["LineasMenu"] = NSNull();
		if (self.lineasMenu != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.lineasMenu!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["LineasMenu"] = arrayOfDictionary;
		}

		
		
		return dictionary;
	}
}

	